// packages/react-map-chart/src/components/MapChart.tsx
import {
  buildMapStyleCss,
  computeTooltipLabel,
  computeTooltipPosition,
  computeTooltipValue,
  getNextInstanceId,
  isSVG,
  type MapData,
  type MapDataValue,
  normalizeMapData,
  registerLocale,
  renderAreaLabels,
  resolveAreaEvent,
  resolveCustomMapSvg,
} from '@map-chart/core'
import {
  Children,
  type CSSProperties,
  type ReactElement,
  type ReactNode,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react'

import { useElementSize } from '../hooks/useElementSize'
import { useMousePosition } from '../hooks/useMousePosition'
import { useStyleTag } from '../hooks/useStyleTag'
import { buildShellCss } from '../shellCss'
import '../styles.css'
import { Tooltip } from './Tooltip'

type AreaCallback = (
  id: string | null,
  value: number | MapDataValue | null | undefined
) => void

export interface MapChartProps {
  langCode?: string
  width?: number | string
  height?: number | string
  mapStyles?: CSSProperties
  displayLegend?: boolean
  displayLegendWhenEmpty?: boolean
  areaNameOnMap?: 'none' | 'all' | 'data-only'
  areaNameOnMapSize?: number
  areaNameOnMapColor?: string
  areaNameOnMapBgColor?: string
  formatValueWithSiPrefix?: boolean
  forceCursorPointer?: boolean
  legendBgColor?: string
  legendTextColor?: string
  legendDividerColor?: string
  legendValuePrefix?: string
  legendValueSuffix?: string
  defaultStrokeColor?: string
  defaultStrokeHoverColor?: string
  defaultFillColor?: string
  defaultFillHoverColor?: string
  baseColor?: string
  customMapSvg?: string
  sanitizeCustomMapSvg?: boolean
  customMapLabels?: Record<string, string>
  data: MapData
  children?: ReactNode
  onMapItemTouchstart?: AreaCallback
  onMapItemMouseover?: AreaCallback
  onMapItemMouseout?: AreaCallback
  onMapItemClick?: AreaCallback
}

export function MapChart({
  langCode = 'en',
  width = '100%',
  height = 500,
  mapStyles = {},
  displayLegend = true,
  displayLegendWhenEmpty = true,
  areaNameOnMap = 'none',
  areaNameOnMapSize = 12,
  areaNameOnMapColor = '#ffffff',
  areaNameOnMapBgColor = 'rgba(0, 0, 0, 0.6)',
  formatValueWithSiPrefix = false,
  forceCursorPointer = false,
  legendBgColor,
  legendTextColor,
  legendDividerColor,
  legendValuePrefix = '',
  legendValueSuffix = '',
  defaultStrokeColor = 'rgb(200, 200, 200)',
  defaultStrokeHoverColor = 'rgb(200, 200, 200)',
  defaultFillColor = 'rgb(236, 236, 236)',
  defaultFillHoverColor = 'rgb(226, 226, 226)',
  baseColor = '#0782c5',
  customMapSvg = '',
  sanitizeCustomMapSvg = true,
  customMapLabels = {},
  data,
  children,
  onMapItemTouchstart,
  onMapItemMouseover,
  onMapItemMouseout,
  onMapItemClick,
}: MapChartProps) {
  const [cpntId] = useState(() => getNextInstanceId())
  const containerId = `v3mc-map-${cpntId}`

  const containerRef = useRef<HTMLDivElement>(null)

  const mapHeight = typeof height === 'string' ? height : `${height}px`
  const mapWidth = typeof width === 'string' ? width : `${width}px`

  const defaultFillHoverColorResolved =
    displayLegend && displayLegendWhenEmpty ? defaultFillHoverColor : defaultFillColor

  const defaultCursor = forceCursorPointer
    ? 'pointer'
    : displayLegend && displayLegendWhenEmpty
      ? 'pointer'
      : 'default'

  const isCustomSvg = useMemo(
    () => !!(customMapSvg && isSVG(customMapSvg)),
    [customMapSvg]
  )

  const normalizedData = useMemo(
    () => normalizeMapData(data, isCustomSvg),
    [data, isCustomSvg]
  )

  // locale
  useEffect(() => {
    registerLocale(langCode)
  }, [langCode])

  // load svg map
  const [svgMap, setSvgMap] = useState('')

  useEffect(() => {
    let cancelled = false

    const load = () => {
      if (customMapSvg) {
        const resolved = resolveCustomMapSvg(customMapSvg, sanitizeCustomMapSvg)
        if (resolved !== null) {
          if (!cancelled) setSvgMap(resolved)
          return
        }
      }

      const child = Children.toArray(children)[0] as ReactElement | undefined
      if (child) {
        if (!cancelled) setSvgMap((child.type as unknown as string) ?? '')
      } else {
        console.warn('No map found')
        if (!cancelled) setSvgMap('')
      }
    }

    load()

    return () => {
      cancelled = true
    }
  }, [customMapSvg, sanitizeCustomMapSvg, children])

  // build map styles — the per-area data-driven fills from @map-chart/core,
  // plus the "shell" (sizing/stroke/fill/hover/cursor) that would be a
  // scoped v-bind() style in Vue but has to be plain CSS text here since it
  // targets the SVG injected via dangerouslySetInnerHTML.
  const setCss = useStyleTag(`${containerId}-styles`)

  useEffect(() => {
    const shellCss = buildShellCss({
      containerId,
      width: mapWidth,
      height: mapHeight,
      defaultStrokeColor,
      defaultFillColor,
      defaultCursor,
      defaultFillHoverColor: defaultFillHoverColorResolved,
      defaultStrokeHoverColor,
    })
    const areaCss = buildMapStyleCss(normalizedData, {
      containerId,
      baseColor,
      displayLegend,
    })
    setCss(shellCss + areaCss)
  }, [
    setCss,
    containerId,
    mapWidth,
    mapHeight,
    defaultStrokeColor,
    defaultFillColor,
    defaultCursor,
    defaultFillHoverColorResolved,
    defaultStrokeHoverColor,
    normalizedData,
    baseColor,
    displayLegend,
  ])

  // handle events
  const [isOutsideMap, setIsOutsideMap] = useState(true)
  const [currentAreaId, setCurrentAreaId] = useState<string | null>(null)
  const [currentAreaValue, setCurrentAreaValue] = useState<
    number | MapDataValue | null | undefined
  >(null)

  useEffect(() => {
    const el = containerRef.current
    if (!el) return

    const emitEvent = (
      target: HTMLElement,
      emitId: 'mapItemMouseover' | 'mapItemMouseout' | 'mapItemClick' | 'mapItemTouchstart'
    ) => {
      const resolved = resolveAreaEvent(target, {
        data: normalizedData,
        langCode,
        isCustomSvg,
      })
      setCurrentAreaId(resolved.id)
      setCurrentAreaValue(resolved.value)

      if (resolved.isValidArea) {
        const callback = {
          mapItemMouseover: onMapItemMouseover,
          mapItemMouseout: onMapItemMouseout,
          mapItemClick: onMapItemClick,
          mapItemTouchstart: onMapItemTouchstart,
        }[emitId]
        callback?.(resolved.id, resolved.value)
        if (emitId === 'mapItemTouchstart') setIsOutsideMap(false)
      } else {
        if (emitId === 'mapItemTouchstart') setIsOutsideMap(true)
      }
    }

    const onTouchstart = (event: Event) =>
      emitEvent(event.target as HTMLElement, 'mapItemTouchstart')
    const onMouseover = (event: Event) =>
      emitEvent(event.target as HTMLElement, 'mapItemMouseover')
    const onMouseout = (event: Event) =>
      emitEvent(event.target as HTMLElement, 'mapItemMouseout')
    const onClick = (event: Event) => emitEvent(event.target as HTMLElement, 'mapItemClick')
    const onMouseEnter = () => setIsOutsideMap(false)
    const onMouseLeave = () => setIsOutsideMap(true)

    el.addEventListener('touchstart', onTouchstart)
    el.addEventListener('mouseover', onMouseover)
    el.addEventListener('mouseout', onMouseout)
    el.addEventListener('click', onClick)
    el.addEventListener('mouseenter', onMouseEnter)
    el.addEventListener('mouseleave', onMouseLeave)

    return () => {
      el.removeEventListener('touchstart', onTouchstart)
      el.removeEventListener('mouseover', onMouseover)
      el.removeEventListener('mouseout', onMouseout)
      el.removeEventListener('click', onClick)
      el.removeEventListener('mouseenter', onMouseEnter)
      el.removeEventListener('mouseleave', onMouseLeave)
    }
  }, [
    normalizedData,
    langCode,
    isCustomSvg,
    onMapItemMouseover,
    onMapItemMouseout,
    onMapItemClick,
    onMapItemTouchstart,
  ])

  // tooltip
  const tooltipLabel = useMemo(
    () =>
      computeTooltipLabel({
        areaId: currentAreaId,
        areaValue: currentAreaValue,
        langCode,
        customMapLabels,
      }),
    [currentAreaId, currentAreaValue, langCode, customMapLabels]
  )

  const tooltipValue = useMemo(
    () =>
      computeTooltipValue({
        areaValue: currentAreaValue,
        formatValueWithSiPrefix,
        legendValuePrefix,
        legendValueSuffix,
      }),
    [currentAreaValue, formatValueWithSiPrefix, legendValuePrefix, legendValueSuffix]
  )

  const displayTooltip = Boolean(
    !isOutsideMap && displayLegend && (displayLegendWhenEmpty || tooltipValue) && tooltipLabel
  )

  const mousePosition = useMousePosition()
  const { ref: tooltipRef, size: tooltipSize } = useElementSize()

  const tooltipPosition = useMemo(
    () =>
      computeTooltipPosition({
        mouseX: mousePosition.x,
        mouseY: mousePosition.y,
        scrollX: window.scrollX,
        scrollY: window.scrollY,
        tooltipWidth: tooltipSize.width,
        tooltipHeight: tooltipSize.height,
        viewportWidth: window.innerWidth,
        viewportHeight: window.innerHeight,
      }),
    [mousePosition, tooltipSize]
  )

  // area name labels — re-rendered (not just created once) whenever data,
  // areaNameOnMap, or the map SVG itself (loaded async in the lite package)
  // change; useEffect always runs after the DOM is committed, so unlike
  // Vue's watcher there's no need for a separate "first render" workaround.
  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    renderAreaLabels(container, {
      areaNameOnMap,
      data: normalizedData,
      langCode,
      isCustomSvg,
      customMapLabels,
      areaNameOnMapSize,
      areaNameOnMapColor,
      areaNameOnMapBgColor,
    })
  }, [
    areaNameOnMap,
    normalizedData,
    langCode,
    isCustomSvg,
    customMapLabels,
    areaNameOnMapSize,
    areaNameOnMapColor,
    areaNameOnMapBgColor,
    svgMap,
  ])

  return (
    <div className="v3mc-container" style={{ height: mapHeight, width: mapWidth }}>
      <div
        id={containerId}
        ref={containerRef}
        className="v3mc-map"
        style={mapStyles}
        dangerouslySetInnerHTML={{ __html: svgMap }}
      />
      {displayTooltip && (
        <Tooltip
          id={`v3mc-tooltip-${cpntId}`}
          innerRef={tooltipRef}
          className="v3mc-tooltip"
          style={{ top: tooltipPosition.top, left: tooltipPosition.left }}
          label={tooltipLabel}
          value={tooltipValue}
          bgColor={legendBgColor}
          textColor={legendTextColor}
          dividerColor={legendDividerColor}
        />
      )}
    </div>
  )
}

// packages/vue3-map-chart/src/components/MapChart.vue
<script setup lang="ts">
  import type { MapData, MapDataValue } from '@/types'
  import {
    buildMapStyleCss,
    computeTooltipLabel,
    computeTooltipPosition,
    computeTooltipValue,
    getNextInstanceId,
    isSVG,
    normalizeMapData,
    registerLocale,
    renderAreaLabels,
    resolveAreaEvent,
    resolveCustomMapSvg,
  } from '@map-chart/core'
  import {
    useElementBounding,
    useEventListener,
    useMouse,
    useMouseInElement,
    useStyleTag,
  } from '@vueuse/core'
  import type { CSSProperties } from 'vue'

  import Tooltip from './Tooltip.vue'

  // handle props

  interface Props {
    langCode?: string
    width?: number | string
    height?: number | string
    mapStyles?: CSSProperties
    displayLegend?: boolean
    displayLegendWhenEmpty?: boolean
    areaNameOnMap?: 'none' | 'all' | 'data-only'
    areaNameOnMapSize?: number
    areaNameOnMapColor?: string
    areaNameOnMapBgColor?: string
    formatValueWithSiPrefix?: boolean
    forceCursorPointer?: boolean
    legendBgColor?: string
    legendTextColor?: string
    legendDividerColor?: string
    legendValuePrefix?: string
    legendValueSuffix?: string
    defaultStrokeColor?: string
    defaultStrokeHoverColor?: string
    defaultFillColor?: string
    defaultFillHoverColor?: string
    baseColor?: string
    customMapSvg?: string
    sanitizeCustomMapSvg?: boolean
    customMapLabels?: Record<string, string>
    data: MapData
  }

  const props = withDefaults(defineProps<Props>(), {
    langCode: 'en',
    height: 500,
    width: '100%',
    mapStyles: () => ({}),
    displayLegend: true,
    displayLegendWhenEmpty: true,
    areaNameOnMap: 'none',
    areaNameOnMapSize: 12,
    areaNameOnMapColor: '#ffffff',
    areaNameOnMapBgColor: 'rgba(0, 0, 0, 0.6)',
    formatValueWithSiPrefix: false,
    forceCursorPointer: false,
    legendBgColor: undefined,
    legendTextColor: undefined,
    legendDividerColor: undefined,
    legendValuePrefix: '',
    legendValueSuffix: '',
    defaultFillColor: 'rgb(236, 236, 236)',
    defaultFillHoverColor: 'rgb(226, 226, 226)',
    defaultStrokeHoverColor: 'rgb(200, 200, 200)',
    defaultStrokeColor: 'rgb(200, 200, 200)',
    baseColor: '#0782c5',
    customMapSvg: '',
    sanitizeCustomMapSvg: true,
    customMapLabels: () => ({}),
  })

  watch(() => props.langCode, registerLocale, { immediate: true })

  const mapHeight = computed(() =>
    typeof props.height === 'string' ? props.height : `${props.height}px`
  )

  const mapWidth = computed(() =>
    typeof props.width === 'string' ? props.width : `${props.width}px`
  )

  const defaultFillColor = computed(() => props.defaultFillColor)

  const defaultFillHoverColor = computed(() =>
    props.displayLegend && props.displayLegendWhenEmpty
      ? props.defaultFillHoverColor
      : props.defaultFillColor
  )

  const defaultStrokeColor = computed(() => props.defaultStrokeColor)

  const defaultCursor = computed(() => {
    if (props.forceCursorPointer) return 'pointer'

    return props.displayLegend && props.displayLegendWhenEmpty
      ? 'pointer'
      : 'default'
  })

  const cpntId = getNextInstanceId()
  const containerId = `v3mc-map-${cpntId}`

  const isCustomSvg = computed(() => !!(props.customMapSvg && isSVG(props.customMapSvg)))

  const normalizedData = computed<MapData>(() =>
    normalizeMapData(props.data, isCustomSvg.value)
  )

  // handle events

  const isOutsideMap = ref(true)
  const currentAreaId = ref<string | null>(null)
  const currentAreaValue = ref<number | MapDataValue | null | undefined>(null)

  const emits = defineEmits([
    'mapItemTouchstart',
    'mapItemMouseover',
    'mapItemMouseout',
    'mapItemClick',
  ])

  onMounted(() => {
    const el = document.getElementById(containerId)
    if (el) {
      const emitEvent = (
        target: HTMLElement,
        emitId:
          | 'mapItemMouseover'
          | 'mapItemMouseout'
          | 'mapItemClick'
          | 'mapItemTouchstart'
      ) => {
        const resolved = resolveAreaEvent(target, {
          data: normalizedData.value,
          langCode: props.langCode,
          isCustomSvg: isCustomSvg.value,
        })
        currentAreaId.value = resolved.id
        currentAreaValue.value = resolved.value

        if (resolved.isValidArea) {
          emits(emitId, resolved.id, resolved.value)
          if (emitId == 'mapItemTouchstart') {
            isOutsideMap.value = false
          }
        } else {
          if (emitId == 'mapItemTouchstart') {
            isOutsideMap.value = true
          }
        }
      }
      useEventListener(el, 'touchstart', (event) => {
        emitEvent(event.target as HTMLElement, 'mapItemTouchstart')
      })
      useEventListener(el, 'mouseover', (event) => {
        emitEvent(event.target as HTMLElement, 'mapItemMouseover')
      })
      useEventListener(el, 'mouseout', (event) => {
        emitEvent(event.target as HTMLElement, 'mapItemMouseout')
      })
      useEventListener(el, 'click', (event) => {
        emitEvent(event.target as HTMLElement, 'mapItemClick')
      })
      const { isOutside } = useMouseInElement(el)
      watch(
        () => isOutside.value,
        (value) => {
          isOutsideMap.value = value
        }
      )
    }
  })

  // load svg map
  const slots = useSlots()
  const svgMap = ref<string | null>(null)

  const loadSvgMap = async (): Promise<void> => {
    if (props.customMapSvg) {
      const resolved = resolveCustomMapSvg(props.customMapSvg, props.sanitizeCustomMapSvg)
      if (resolved !== null) {
        svgMap.value = resolved
        return
      }
    }

    if (slots.default) {
      const slotContent = slots.default()

      svgMap.value = slotContent[0]?.type as string
    } else {
      console.warn('No map found')
      svgMap.value = ''
    }
  }

  watch(
    () => slots.default,
    () => {
      loadSvgMap()
    },
    { immediate: true, deep: true }
  )

  // build map styles

  const { css } = useStyleTag('', {
    id: `${containerId}-styles`,
  })

  const buildStyles = () => {
    css.value = buildMapStyleCss(normalizedData.value, {
      containerId,
      baseColor: props.baseColor,
      displayLegend: props.displayLegend,
    })
  }

  watch(
    () => props.data,
    () => {
      buildStyles()
    },
    { deep: true, immediate: true }
  )

  // tooltip

  const tooltipLabel = computed(() =>
    computeTooltipLabel({
      areaId: currentAreaId.value,
      areaValue: currentAreaValue.value,
      langCode: props.langCode,
      customMapLabels: props.customMapLabels,
    })
  )

  const tooltipValue = computed(() =>
    computeTooltipValue({
      areaValue: currentAreaValue.value,
      formatValueWithSiPrefix: props.formatValueWithSiPrefix,
      legendValuePrefix: props.legendValuePrefix,
      legendValueSuffix: props.legendValueSuffix,
    })
  )

  const displayTooltip = computed(() => {
    return (
      !isOutsideMap.value &&
      props.displayLegend &&
      (props.displayLegendWhenEmpty || tooltipValue.value) &&
      tooltipLabel.value
    )
  })

  const tooltip = ref()
  const { x: mouseX, y: mouseY } = useMouse()
  const { width: tooltipWidth, height: tooltipHeight } = useElementBounding(
    tooltip as any
  )

  const tooltipPosition = computed(() =>
    computeTooltipPosition({
      mouseX: mouseX.value,
      mouseY: mouseY.value,
      scrollX: window.scrollX,
      scrollY: window.scrollY,
      tooltipWidth: tooltipWidth.value,
      tooltipHeight: tooltipHeight.value,
      viewportWidth: window.innerWidth,
      viewportHeight: window.innerHeight,
    })
  )

  const tooltipLeft = computed(() => tooltipPosition.value.left)
  const tooltipTop = computed(() => tooltipPosition.value.top)

  // Dynamically Display area name on map

  // Labels are rebuilt (not just created once) so they stay in sync when `data`
  // arrives/changes after mount, when `areaNameOnMap` is toggled, or when the
  // map SVG itself loads asynchronously (vue3-map-chart-lite fetches it after mount).
  const renderLabels = () => {
    const mapContainer = document.getElementById(containerId)
    if (!mapContainer) return

    renderAreaLabels(mapContainer, {
      areaNameOnMap: props.areaNameOnMap,
      data: normalizedData.value,
      langCode: props.langCode,
      isCustomSvg: isCustomSvg.value,
      customMapLabels: props.customMapLabels,
      areaNameOnMapSize: props.areaNameOnMapSize,
      areaNameOnMapColor: props.areaNameOnMapColor,
      areaNameOnMapBgColor: props.areaNameOnMapBgColor,
    })
  }

  // An immediate watcher's first call runs synchronously during setup, before
  // the component has actually mounted (flush: 'post' only changes the timing
  // of *subsequent* runs) — so the first render has to go through onMounted
  // instead, where the container is guaranteed to exist.
  onMounted(renderLabels)

  watch([() => props.areaNameOnMap, () => props.data, svgMap], renderLabels, {
    deep: true,
    flush: 'post',
  })
</script>

<template>
  <div class="v3mc-container">
    <div
      :id="containerId"
      class="v3mc-map"
      :style="mapStyles"
      v-html="svgMap"></div>
    <Tooltip
      v-if="displayTooltip"
      :id="`v3mc-tooltip-${cpntId}`"
      ref="tooltip"
      class="v3mc-tooltip"
      :label="tooltipLabel"
      :value="tooltipValue"
      :bg-color="props.legendBgColor"
      :text-color="props.legendTextColor"
      :divider-color="props.legendDividerColor" />
  </div>
</template>

<style scoped>
  .v3mc-container {
    padding: 5px;
    position: relative;
  }

  .v3mc-container,
  :deep(.v3mc-map > svg) {
    height: v-bind(mapHeight);
    width: v-bind(mapWidth);
  }

  :deep(.v3mc-map > svg) {
    stroke: v-bind(defaultStrokeColor);
    fill: v-bind(defaultFillColor);
    stroke-width: 0.4px;
  }

  :deep(.v3mc-map > svg > path) {
    cursor: v-bind(defaultCursor);
  }

  :deep(.v3mc-map > svg > path:hover) {
    fill: v-bind(defaultFillHoverColor);
    stroke: v-bind(defaultStrokeHoverColor);
    stroke-width: 0.5px;
  }

  .v3mc-tooltip {
    position: fixed;
    z-index: 9999;
    top: v-bind(tooltipTop);
    left: v-bind(tooltipLeft);
  }
</style>
